

spring:
  application:
    name: nutrition-service
  config:
    #import: optional:configserver:http://localhost:8071
    #import: optional:configserver:http://config-server:8071
    import: optional:configserver:http://config-server.fittrack.local:8071


