spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://keycloak:8080/realms/fitness-oauth2
          #jwk-set-uri: http://keycloak:8080/realms/fitness-oauth2/protocol/openid-connect/certs
          #jwk-set-uri: http://keycloak.fittrack.local:8080/realms/fitness-oauth2/protocol/openid-connect/certs
          issuer-uri: https://auth.fitnesstrackapp.click/realms/fitness-oauth2
#          issuer-uri: https://keycloak.fittrack.local:8080/realms/fitness-oauth2

  cloud:
    config:
      uri: http://config-server.fittrack.local:8071
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: USER-SERVICE
          uri: lb://user-service
          predicates:
            - Path=/api/users/**


        - id: ACTIVITY-SERVICE
          uri: lb://activity-service
          predicates:
            - Path=/api/activities/**

        - id: RECOMMENDATION-SERVICE
          uri: lb://recommendation-service
          predicates:
            - Path=/api/recommendations/**

        - id: nutrition-service
          uri: lb://nutrition-service
          predicates:
            - Path=/api/nutrition/**, /api/nutritionRecommendations/**


server:
  port: 8080

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info
#  endpoint:
#    health:
#      show-details: never
#      probes:
#        enabled: true
management:
  health:
    defaults:
      enabled: true
    reactive:
      enabled: false
    keycloak:
      enabled: false

eureka:
  client:
    serviceUrl:
      #defaultZone: http://eureka-server:8761/eureka/
      defaultZone: http://eureka-server.fittrack.local:8761/eureka/
  instance:
#    hostname: eureka-server
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

