spring:
  application:
    name: API-GATEWAY
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/fitness-oauth2/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**


        - id: ACTIVITY-SERVICE
          uri: lb://ACTIVITY-SERVICE
          predicates:
            - Path=/api/activities/**

        - id: RECOMMENDATION-SERVICE
          uri: lb://RECOMMENDATION-SERVICE
          predicates:
            - Path=/api/recommendations/**

        - id: nutrition-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/nutrition/**, /api/nutritionRecommendations/**


server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}

