server:
  port: 8083

spring:
  data:
    mongodb:
     # uri: mongodb://localhost:27017/fitness-recommendation-db
      #uri: mongodb://mongodb:27017/recommendationdb
      uri: mongodb://mongodb.fittrack.local:27017/recommendationdb


  rabbitmq:
    #host: rabbitmq
    host: rabbitmq.fittrack.local
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
        concurrency: 1
        max-concurrency: 1

eureka:
  client:
    serviceUrl:
      #defaultZone: http://eureka-server:8761/eureka/
      defaultZone: http://eureka-server.fittrack.local:8761/eureka/
  instance:
#    hostname: eureka-server
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
  delete:
    queue: activity.deleted.queue
    routing:
      key: activity.deleted

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}

